spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---
spring:
    config:
        activate:
            on-profile: prod
    jpa:
      hibernate:
        ddl-auto: none
      generate-ddl: false

server:
  http2:
    enabled: true
